package com.zhangke.shizhong.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "APPLICATION_INFO".
*/
public class ApplicationInfoDao extends AbstractDao<ApplicationInfo, Long> {

    public static final String TABLENAME = "APPLICATION_INFO";

    /**
     * Properties of entity ApplicationInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property AppName = new Property(1, String.class, "appName", false, "APP_NAME");
        public final static Property PackageName = new Property(2, String.class, "packageName", false, "PACKAGE_NAME");
        public final static Property VersionName = new Property(3, String.class, "versionName", false, "VERSION_NAME");
        public final static Property VersionCode = new Property(4, int.class, "versionCode", false, "VERSION_CODE");
        public final static Property SortTarget = new Property(5, String.class, "sortTarget", false, "SORT_TARGET");
        public final static Property IsSystemApp = new Property(6, boolean.class, "isSystemApp", false, "IS_SYSTEM_APP");
    }


    public ApplicationInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ApplicationInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"APPLICATION_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"APP_NAME\" TEXT," + // 1: appName
                "\"PACKAGE_NAME\" TEXT," + // 2: packageName
                "\"VERSION_NAME\" TEXT," + // 3: versionName
                "\"VERSION_CODE\" INTEGER NOT NULL ," + // 4: versionCode
                "\"SORT_TARGET\" TEXT," + // 5: sortTarget
                "\"IS_SYSTEM_APP\" INTEGER NOT NULL );"); // 6: isSystemApp
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"APPLICATION_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ApplicationInfo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String appName = entity.getAppName();
        if (appName != null) {
            stmt.bindString(2, appName);
        }
 
        String packageName = entity.getPackageName();
        if (packageName != null) {
            stmt.bindString(3, packageName);
        }
 
        String versionName = entity.getVersionName();
        if (versionName != null) {
            stmt.bindString(4, versionName);
        }
        stmt.bindLong(5, entity.getVersionCode());
 
        String sortTarget = entity.getSortTarget();
        if (sortTarget != null) {
            stmt.bindString(6, sortTarget);
        }
        stmt.bindLong(7, entity.getIsSystemApp() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ApplicationInfo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String appName = entity.getAppName();
        if (appName != null) {
            stmt.bindString(2, appName);
        }
 
        String packageName = entity.getPackageName();
        if (packageName != null) {
            stmt.bindString(3, packageName);
        }
 
        String versionName = entity.getVersionName();
        if (versionName != null) {
            stmt.bindString(4, versionName);
        }
        stmt.bindLong(5, entity.getVersionCode());
 
        String sortTarget = entity.getSortTarget();
        if (sortTarget != null) {
            stmt.bindString(6, sortTarget);
        }
        stmt.bindLong(7, entity.getIsSystemApp() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public ApplicationInfo readEntity(Cursor cursor, int offset) {
        ApplicationInfo entity = new ApplicationInfo( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // appName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // packageName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // versionName
            cursor.getInt(offset + 4), // versionCode
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // sortTarget
            cursor.getShort(offset + 6) != 0 // isSystemApp
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ApplicationInfo entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setAppName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPackageName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setVersionName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setVersionCode(cursor.getInt(offset + 4));
        entity.setSortTarget(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIsSystemApp(cursor.getShort(offset + 6) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ApplicationInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ApplicationInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ApplicationInfo entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
