package com.zhangke.shizhong.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhangke.shizhong.db.ApplicationInfo;
import com.zhangke.shizhong.db.ClockRecord;
import com.zhangke.shizhong.db.Plan;

import com.zhangke.shizhong.db.ApplicationInfoDao;
import com.zhangke.shizhong.db.ClockRecordDao;
import com.zhangke.shizhong.db.PlanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig applicationInfoDaoConfig;
    private final DaoConfig clockRecordDaoConfig;
    private final DaoConfig planDaoConfig;

    private final ApplicationInfoDao applicationInfoDao;
    private final ClockRecordDao clockRecordDao;
    private final PlanDao planDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        applicationInfoDaoConfig = daoConfigMap.get(ApplicationInfoDao.class).clone();
        applicationInfoDaoConfig.initIdentityScope(type);

        clockRecordDaoConfig = daoConfigMap.get(ClockRecordDao.class).clone();
        clockRecordDaoConfig.initIdentityScope(type);

        planDaoConfig = daoConfigMap.get(PlanDao.class).clone();
        planDaoConfig.initIdentityScope(type);

        applicationInfoDao = new ApplicationInfoDao(applicationInfoDaoConfig, this);
        clockRecordDao = new ClockRecordDao(clockRecordDaoConfig, this);
        planDao = new PlanDao(planDaoConfig, this);

        registerDao(ApplicationInfo.class, applicationInfoDao);
        registerDao(ClockRecord.class, clockRecordDao);
        registerDao(Plan.class, planDao);
    }
    
    public void clear() {
        applicationInfoDaoConfig.clearIdentityScope();
        clockRecordDaoConfig.clearIdentityScope();
        planDaoConfig.clearIdentityScope();
    }

    public ApplicationInfoDao getApplicationInfoDao() {
        return applicationInfoDao;
    }

    public ClockRecordDao getClockRecordDao() {
        return clockRecordDao;
    }

    public PlanDao getPlanDao() {
        return planDao;
    }

}
